# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basicValues.ui',
# licensing of 'basicValues.ui' applies.
#
# Created: Wed Oct 27 13:33:09 2021
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(461, 686)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerlabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.headerlabel.setFont(font)
        self.headerlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.headerlabel.setObjectName("headerlabel")
        self.verticalLayout_2.addWidget(self.headerlabel)
        self.mmnote = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.mmnote.setFont(font)
        self.mmnote.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.mmnote.setObjectName("mmnote")
        self.verticalLayout_2.addWidget(self.mmnote)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Box_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Box_label.sizePolicy().hasHeightForWidth())
        self.Box_label.setSizePolicy(sizePolicy)
        self.Box_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Box_label.setObjectName("Box_label")
        self.verticalLayout.addWidget(self.Box_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.boxW = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxW.sizePolicy().hasHeightForWidth())
        self.boxW.setSizePolicy(sizePolicy)
        self.boxW.setObjectName("boxW")
        self.horizontalLayout.addWidget(self.boxW)
        self.boxW_val = QtWidgets.QSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxW_val.sizePolicy().hasHeightForWidth())
        self.boxW_val.setSizePolicy(sizePolicy)
        self.boxW_val.setMinimum(1)
        self.boxW_val.setMaximum(1000)
        self.boxW_val.setObjectName("boxW_val")
        self.horizontalLayout.addWidget(self.boxW_val)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.inside_chk = QtWidgets.QCheckBox(Dialog)
        self.inside_chk.setObjectName("inside_chk")
        self.horizontalLayout_2.addWidget(self.inside_chk)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.boxY = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxY.sizePolicy().hasHeightForWidth())
        self.boxY.setSizePolicy(sizePolicy)
        self.boxY.setObjectName("boxY")
        self.horizontalLayout_3.addWidget(self.boxY)
        self.boxY_val = QtWidgets.QSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxY_val.sizePolicy().hasHeightForWidth())
        self.boxY_val.setSizePolicy(sizePolicy)
        self.boxY_val.setMinimum(1)
        self.boxY_val.setMaximum(1000)
        self.boxY_val.setObjectName("boxY_val")
        self.horizontalLayout_3.addWidget(self.boxY_val)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.coord_note = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coord_note.sizePolicy().hasHeightForWidth())
        self.coord_note.setSizePolicy(sizePolicy)
        self.coord_note.setObjectName("coord_note")
        self.horizontalLayout_4.addWidget(self.coord_note)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.boxZ = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxZ.sizePolicy().hasHeightForWidth())
        self.boxZ.setSizePolicy(sizePolicy)
        self.boxZ.setObjectName("boxZ")
        self.horizontalLayout_5.addWidget(self.boxZ)
        self.boxZ_val = QtWidgets.QSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxZ_val.sizePolicy().hasHeightForWidth())
        self.boxZ_val.setSizePolicy(sizePolicy)
        self.boxZ_val.setMinimum(1)
        self.boxZ_val.setMaximum(1000)
        self.boxZ_val.setObjectName("boxZ_val")
        self.horizontalLayout_5.addWidget(self.boxZ_val)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Stock_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stock_label.sizePolicy().hasHeightForWidth())
        self.Stock_label.setSizePolicy(sizePolicy)
        self.Stock_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Stock_label.setObjectName("Stock_label")
        self.verticalLayout_3.addWidget(self.Stock_label)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.stockX = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockX.sizePolicy().hasHeightForWidth())
        self.stockX.setSizePolicy(sizePolicy)
        self.stockX.setObjectName("stockX")
        self.horizontalLayout_7.addWidget(self.stockX)
        self.StockX_val = QtWidgets.QSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StockX_val.sizePolicy().hasHeightForWidth())
        self.StockX_val.setSizePolicy(sizePolicy)
        self.StockX_val.setMinimum(1)
        self.StockX_val.setMaximum(50)
        self.StockX_val.setObjectName("StockX_val")
        self.horizontalLayout_7.addWidget(self.StockX_val)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.stockY = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockY.sizePolicy().hasHeightForWidth())
        self.stockY.setSizePolicy(sizePolicy)
        self.stockY.setObjectName("stockY")
        self.horizontalLayout_9.addWidget(self.stockY)
        self.stockY_val = QtWidgets.QSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockY_val.sizePolicy().hasHeightForWidth())
        self.stockY_val.setSizePolicy(sizePolicy)
        self.stockY_val.setMinimum(1)
        self.stockY_val.setMaximum(1000)
        self.stockY_val.setObjectName("stockY_val")
        self.horizontalLayout_9.addWidget(self.stockY_val)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.stockZ = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockZ.sizePolicy().hasHeightForWidth())
        self.stockZ.setSizePolicy(sizePolicy)
        self.stockZ.setObjectName("stockZ")
        self.horizontalLayout_11.addWidget(self.stockZ)
        self.stockZ_val = QtWidgets.QDoubleSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockZ_val.sizePolicy().hasHeightForWidth())
        self.stockZ_val.setSizePolicy(sizePolicy)
        self.stockZ_val.setDecimals(1)
        self.stockZ_val.setMaximum(50.0)
        self.stockZ_val.setSingleStep(0.1)
        self.stockZ_val.setObjectName("stockZ_val")
        self.horizontalLayout_11.addWidget(self.stockZ_val)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.precision_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.precision_label.sizePolicy().hasHeightForWidth())
        self.precision_label.setSizePolicy(sizePolicy)
        self.precision_label.setObjectName("precision_label")
        self.horizontalLayout_12.addWidget(self.precision_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.endMill = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endMill.sizePolicy().hasHeightForWidth())
        self.endMill.setSizePolicy(sizePolicy)
        self.endMill.setFrameShape(QtWidgets.QFrame.Box)
        self.endMill.setObjectName("endMill")
        self.verticalLayout_4.addWidget(self.endMill)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.emDia = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emDia.sizePolicy().hasHeightForWidth())
        self.emDia.setSizePolicy(sizePolicy)
        self.emDia.setObjectName("emDia")
        self.horizontalLayout_13.addWidget(self.emDia)
        self.emDia_val = QtWidgets.QDoubleSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emDia_val.sizePolicy().hasHeightForWidth())
        self.emDia_val.setSizePolicy(sizePolicy)
        self.emDia_val.setDecimals(1)
        self.emDia_val.setMinimum(0.1)
        self.emDia_val.setMaximum(12.5)
        self.emDia_val.setSingleStep(0.1)
        self.emDia_val.setObjectName("emDia_val")
        self.horizontalLayout_13.addWidget(self.emDia_val)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.downcut = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downcut.sizePolicy().hasHeightForWidth())
        self.downcut.setSizePolicy(sizePolicy)
        self.downcut.setObjectName("downcut")
        self.horizontalLayout_14.addWidget(self.downcut)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem8)
        self.cancelBtn = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelBtn.sizePolicy().hasHeightForWidth())
        self.cancelBtn.setSizePolicy(sizePolicy)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_15.addWidget(self.cancelBtn)
        self.useBtn = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useBtn.sizePolicy().hasHeightForWidth())
        self.useBtn.setSizePolicy(sizePolicy)
        self.useBtn.setObjectName("useBtn")
        self.horizontalLayout_15.addWidget(self.useBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Box Dimensions", None, -1))
        self.headerlabel.setText(QtWidgets.QApplication.translate("Dialog", "Tabbed Box Workbench", None, -1))
        self.mmnote.setText(QtWidgets.QApplication.translate("Dialog", "[All dimensions are in mm]", None, -1))
        self.Box_label.setText(QtWidgets.QApplication.translate("Dialog", "Box Dimensions", None, -1))
        self.boxW.setText(QtWidgets.QApplication.translate("Dialog", "Width (X) ", None, -1))
        self.inside_chk.setText(QtWidgets.QApplication.translate("Dialog", "Inside Size", None, -1))
        self.boxY.setText(QtWidgets.QApplication.translate("Dialog", "Depth (Y) ", None, -1))
        self.coord_note.setText(QtWidgets.QApplication.translate("Dialog", "values match standard\n"
"3D view", None, -1))
        self.boxZ.setText(QtWidgets.QApplication.translate("Dialog", "Height (Z) ", None, -1))
        self.Stock_label.setText(QtWidgets.QApplication.translate("Dialog", "Stock Dimensions", None, -1))
        self.stockX.setText(QtWidgets.QApplication.translate("Dialog", "Stock Width (X) ", None, -1))
        self.stockY.setText(QtWidgets.QApplication.translate("Dialog", "Stock Depth (Y)", None, -1))
        self.stockZ.setText(QtWidgets.QApplication.translate("Dialog", "Stock Thickness (Z)", None, -1))
        self.precision_label.setText(QtWidgets.QApplication.translate("Dialog", "Be very precise in measuring\n"
"stock thickness", None, -1))
        self.endMill.setText(QtWidgets.QApplication.translate("Dialog", "End Mill Data", None, -1))
        self.emDia.setText(QtWidgets.QApplication.translate("Dialog", "End Mill Diameter", None, -1))
        self.downcut.setText(QtWidgets.QApplication.translate("Dialog", "downcut strongly\n"
"recommended", None, -1))
        self.cancelBtn.setText(QtWidgets.QApplication.translate("Dialog", "Cancel", None, -1))
        self.useBtn.setText(QtWidgets.QApplication.translate("Dialog", "Use This", None, -1))

