# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gallery.ui',
# licensing of 'gallery.ui' applies.
#
# Created: Tue Nov  2 10:09:21 2021
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_dlog(object):
    def setupUi(self, dlog):
        dlog.setObjectName("dlog")
        dlog.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        dlog.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(dlog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 322, 225))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.headerLbl = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerLbl.sizePolicy().hasHeightForWidth())
        self.headerLbl.setSizePolicy(sizePolicy)
        self.headerLbl.setFrameShape(QtWidgets.QFrame.Box)
        self.headerLbl.setLineWidth(2)
        self.headerLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.headerLbl.setObjectName("headerLbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.headerLbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainBoxImg = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainBoxImg.sizePolicy().hasHeightForWidth())
        self.plainBoxImg.setSizePolicy(sizePolicy)
        self.plainBoxImg.setText("")
        self.plainBoxImg.setPixmap(QtGui.QPixmap("../PlainCube_box_pixmap.png"))
        self.plainBoxImg.setObjectName("plainBoxImg")
        self.verticalLayout.addWidget(self.plainBoxImg)
        self.plainBoxLbl = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainBoxLbl.sizePolicy().hasHeightForWidth())
        self.plainBoxLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.plainBoxLbl.setFont(font)
        self.plainBoxLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.plainBoxLbl.setObjectName("plainBoxLbl")
        self.verticalLayout.addWidget(self.plainBoxLbl)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toplessBoxImg = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toplessBoxImg.sizePolicy().hasHeightForWidth())
        self.toplessBoxImg.setSizePolicy(sizePolicy)
        self.toplessBoxImg.setText("")
        self.toplessBoxImg.setPixmap(QtGui.QPixmap("../ToplessCube_box_pixmap.png"))
        self.toplessBoxImg.setObjectName("toplessBoxImg")
        self.verticalLayout_2.addWidget(self.toplessBoxImg)
        self.toplessBoxLbl = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toplessBoxLbl.sizePolicy().hasHeightForWidth())
        self.toplessBoxLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.toplessBoxLbl.setFont(font)
        self.toplessBoxLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.toplessBoxLbl.setObjectName("toplessBoxLbl")
        self.verticalLayout_2.addWidget(self.toplessBoxLbl)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        self.doneBtn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doneBtn.sizePolicy().hasHeightForWidth())
        self.doneBtn.setSizePolicy(sizePolicy)
        self.doneBtn.setDefault(True)
        self.doneBtn.setObjectName("doneBtn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.doneBtn)

        self.retranslateUi(dlog)
        QtCore.QMetaObject.connectSlotsByName(dlog)

    def retranslateUi(self, dlog):
        dlog.setWindowTitle(QtWidgets.QApplication.translate("dlog", "Box Variant Gallery", None, -1))
        self.headerLbl.setText(QtWidgets.QApplication.translate("dlog", "Box Variant Gallery", None, -1))
        self.plainBoxLbl.setText(QtWidgets.QApplication.translate("dlog", "Plain Box", None, -1))
        self.toplessBoxLbl.setText(QtWidgets.QApplication.translate("dlog", "Topless Box", None, -1))
        self.doneBtn.setText(QtWidgets.QApplication.translate("dlog", "Done", None, -1))

