# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simpleBox.ui',
# licensing of 'simpleBox.ui' applies.
#
# Created: Sat Nov 13 15:26:05 2021
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.header = QtWidgets.QLabel(Dialog)
        self.header.setGeometry(QtCore.QRect(100, 10, 181, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.header.setFont(font)
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.buildBtn = QtWidgets.QPushButton(Dialog)
        self.buildBtn.setGeometry(QtCore.QRect(30, 250, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buildBtn.sizePolicy().hasHeightForWidth())
        self.buildBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.buildBtn.setFont(font)
        self.buildBtn.setDefault(True)
        self.buildBtn.setObjectName("buildBtn")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 359, 96))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabSizeLbl = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSizeLbl.sizePolicy().hasHeightForWidth())
        self.tabSizeLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tabSizeLbl.setFont(font)
        self.tabSizeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.tabSizeLbl.setObjectName("tabSizeLbl")
        self.verticalLayout_4.addWidget(self.tabSizeLbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.minSizeValLbl = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minSizeValLbl.sizePolicy().hasHeightForWidth())
        self.minSizeValLbl.setSizePolicy(sizePolicy)
        self.minSizeValLbl.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.minSizeValLbl.setFont(font)
        self.minSizeValLbl.setFrameShape(QtWidgets.QFrame.Box)
        self.minSizeValLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.minSizeValLbl.setObjectName("minSizeValLbl")
        self.verticalLayout.addWidget(self.minSizeValLbl)
        self.minSizeLbl = QtWidgets.QLabel(self.layoutWidget)
        self.minSizeLbl.setMinimumSize(QtCore.QSize(53, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.minSizeLbl.setFont(font)
        self.minSizeLbl.setObjectName("minSizeLbl")
        self.verticalLayout.addWidget(self.minSizeLbl)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.userSizeVal = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.userSizeVal.setFont(font)
        self.userSizeVal.setObjectName("userSizeVal")
        self.verticalLayout_2.addWidget(self.userSizeVal)
        self.userSizeLbl = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userSizeLbl.sizePolicy().hasHeightForWidth())
        self.userSizeLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.userSizeLbl.setFont(font)
        self.userSizeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.userSizeLbl.setObjectName("userSizeLbl")
        self.verticalLayout_2.addWidget(self.userSizeLbl)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.maxSizeVal = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxSizeVal.sizePolicy().hasHeightForWidth())
        self.maxSizeVal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.maxSizeVal.setFont(font)
        self.maxSizeVal.setFrameShape(QtWidgets.QFrame.Box)
        self.maxSizeVal.setAlignment(QtCore.Qt.AlignCenter)
        self.maxSizeVal.setObjectName("maxSizeVal")
        self.verticalLayout_3.addWidget(self.maxSizeVal)
        self.maxSizeLbl = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxSizeLbl.sizePolicy().hasHeightForWidth())
        self.maxSizeLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.maxSizeLbl.setFont(font)
        self.maxSizeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.maxSizeLbl.setObjectName("maxSizeLbl")
        self.verticalLayout_3.addWidget(self.maxSizeLbl)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabCtVal = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabCtVal.sizePolicy().hasHeightForWidth())
        self.tabCtVal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tabCtVal.setFont(font)
        self.tabCtVal.setFrameShape(QtWidgets.QFrame.Box)
        self.tabCtVal.setObjectName("tabCtVal")
        self.verticalLayout_5.addWidget(self.tabCtVal)
        self.tabCtLbl = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabCtLbl.sizePolicy().hasHeightForWidth())
        self.tabCtLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.tabCtLbl.setFont(font)
        self.tabCtLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.tabCtLbl.setObjectName("tabCtLbl")
        self.verticalLayout_5.addWidget(self.tabCtLbl)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.sizeNote = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizeNote.sizePolicy().hasHeightForWidth())
        self.sizeNote.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.sizeNote.setFont(font)
        self.sizeNote.setObjectName("sizeNote")
        self.horizontalLayout.addWidget(self.sizeNote)
        self.verticalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.header.setText(QtWidgets.QApplication.translate("Dialog", "Simple Box Settings", None, -1))
        self.buildBtn.setText(QtWidgets.QApplication.translate("Dialog", "Build", None, -1))
        self.tabSizeLbl.setText(QtWidgets.QApplication.translate("Dialog", "Tab Size", None, -1))
        self.minSizeValLbl.setText(QtWidgets.QApplication.translate("Dialog", "00", None, -1))
        self.minSizeLbl.setText(QtWidgets.QApplication.translate("Dialog", "Minimum\n"
"Size", None, -1))
        self.userSizeLbl.setText(QtWidgets.QApplication.translate("Dialog", "Your Size\n"
"(mm)", None, -1))
        self.maxSizeVal.setText(QtWidgets.QApplication.translate("Dialog", "00", None, -1))
        self.maxSizeLbl.setText(QtWidgets.QApplication.translate("Dialog", "Maximum\n"
"Size", None, -1))
        self.tabCtVal.setText(QtWidgets.QApplication.translate("Dialog", "00", None, -1))
        self.tabCtLbl.setText(QtWidgets.QApplication.translate("Dialog", "Min. Tab\n"
"Count", None, -1))
        self.sizeNote.setText(QtWidgets.QApplication.translate("Dialog", "Size will be\n"
"adjusted for a\n"
"whole number\n"
"of tabs", None, -1))

